import {
  product1,
  product2,
  product3,
  product4,
  dress1,
  dress2,
  dress3,
  dress4,
  dress5,
  dress6,
  dress7,
  categorySaleFoto,
  categoryFoto1,
  categoryFoto2,
  categoryFoto3,
  categoryFoto4,
  categoryFoto5,
  categoryFoto6,
  categoryFoto7,
  categoryFoto8,
  collectionFoto,
  collectionFoto1,
  collectionFoto2,
  collectionFoto3,
} from "./constants";

const productsBD = [
  {
    img: categorySaleFoto,
    imgs: [
      categorySaleFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Продукт",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "12",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "sale",
    collection: "cruise",
  },
  {
    img: product1,
    imgs: [
      product1,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Коралловое платье с плиссированными вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 15500,
    price: 8000,
    id: "1",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "urban",
  },
  {
    img: product2,
    imgs: [
      product2,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Брюки с эффектом джинсовой ткани",
    article: "PP29",
    size: "S",
    height: 160,
    quantity: 1,
    discount: "",
    price: 20000,
    id: "2",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "pant",
    collection: "punk",
  },
  {
    img: product3,
    imgs: [
      product3,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Коралловое платье с плиссированными вставками",
    article: "PP13",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 18000,
    id: "3",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: product4,
    imgs: [
      product4,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Бордовое платье [x1]",
    article: "PP13",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 11000,
    price: 9000,
    id: "4",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress1,
    imgs: [
      dress1,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Синее плиссированное платье с вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "5",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress2,
    imgs: [
      dress2,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Розовое плиссированное платье с вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 50000,
    price: 35000,
    id: "6",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress3,
    imgs: [
      dress3,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Темно-синее платье с воланами",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "7",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress4,
    imgs: [
      dress4,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Песочное платье с плиссированными вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "8",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress5,
    imgs: [
      dress5,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Розовое плиссированное платье с вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 45000,
    price: 35000,
    id: "9",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress6,
    imgs: [
      dress6,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Бордовое платье",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "10",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress7,
    imgs: [
      dress7,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Коралловое платье с плиссированными вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 43000,
    price: 35000,
    id: "11",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: categoryFoto1,
    imgs: [
      categoryFoto1,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Жакет",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "13",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "jackets",
    collection: "cruise",
  },
  {
    img: categoryFoto2,
    imgs: [
      categoryFoto2,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Юбка",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "14",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "skirts",
    collection: "urban",
  },
  {
    img: categoryFoto3,
    imgs: [
      categoryFoto3,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Свадебное платье",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 60000,
    price: 35000,
    id: "15",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "wedding",
    collection: "urban",
  },
  {
    img: categoryFoto4,
    imgs: [
      categoryFoto4,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Блузка",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "16",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "blouses",
    collection: "punk",
  },
  {
    img: categoryFoto5,
    imgs: [
      categoryFoto5,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Костюм",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "17",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "costumes",
    collection: "cruise",
  },
  {
    img: categoryFoto6,
    imgs: [
      categoryFoto6,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Свитер",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 43000,
    price: 35000,
    id: "18",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "sweaters",
    collection: "cruise",
  },
  {
    img: categoryFoto7,
    imgs: [
      categoryFoto7,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Верхняя одежда",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "19",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "outerwear",
    collection: "cruise",
  },
  {
    img: categoryFoto8,
    imgs: [
      categoryFoto8,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Футболка",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "20",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "tshirt",
    collection: "punk",
  },
  {
    img: collectionFoto,
    imgs: [
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Олимпийка",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "21",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "olympians",
    collection: "punk",
  },
  {
    img: collectionFoto,
    imgs: [
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Худи",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "23",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "hoodies",
    collection: "punk",
  },
  {
    img: collectionFoto,
    imgs: [
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Водолазка",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "24",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "turtlenecks",
    collection: "punk",
  },
  {
    img: collectionFoto,
    imgs: [
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
      collectionFoto,
    ],
    title: "Аксессуар",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 47000,
    price: 35000,
    id: "25",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "accessories",
    collection: "urban",
  },
];

const categoryBD = [
  { id: "101", src: categorySaleFoto, title: "Распродажа", path: "sale" },
  { id: "102", src: dress1, title: "Платья", path: "dress" },
  { id: "103", src: categoryFoto1, title: "Жакеты", path: "jackets" },
  { id: "104", src: categoryFoto2, title: "Юбки", path: "skirts" },
  { id: "105", src: categoryFoto3, title: "Свадебные платья", path: "wedding" },
  { id: "106", src: categoryFoto4, title: "блузки", path: "blouses" },
  { id: "107", src: categoryFoto5, title: "Костюмы", path: "costumes" },
  { id: "108", src: categoryFoto6, title: "Свитеры", path: "sweaters" },
  { id: "109", src: categoryFoto7, title: "Верхняя одежда", path: "outerwear" },
  { id: "110", src: categoryFoto8, title: "Футболки", path: "tshirt" },
  { id: "111", src: collectionFoto, title: "Олимпийки", path: "olympians" },
  { id: "112", src: collectionFoto, title: "Худи и свитшоты", path: "hoodies" },
  { id: "113", src: collectionFoto, title: "Брюки", path: "pant" },
  { id: "114", src: collectionFoto, title: "Водолазки", path: "turtlenecks" },
  { id: "115", src: collectionFoto, title: "Аксессуары", path: "accessories" },
];

const collectionBD = [
  {
    id: "200",
    src: collectionFoto1,
    title: "Городская мода",
    path: "urban",
    text: "Приталенное платье мини мятного цвета в полу-спортивном стиле. Выполнено из джерси, рукава из мерцающего желтого крепа. На юбке вставки из гофре плиссе разных цветов. ",
  },
  {
    id: "201",
    src: collectionFoto2,
    title: "Панк-кутюр",
    path: "punk",
    text: "Мятный и розовый лампасы придают платью спортивное направление. По спинке длинная леопардовая молния.",
  },
  {
    id: "202",
    src: collectionFoto3,
    title: "круиз 2022",
    path: "cruise",
    text: "Приталенное платье мини мятного цвета в полу-спортивном стиле. Выполнено из джерси, рукава из мерцающего желтого крепа. На юбке вставки из гофре плиссе разных цветов. Мятный и розовый лампасы придают платью спортивное направление. По спинке длинная леопардовая молния.",
  },
  {
    id: "203",
    src: collectionFoto,
    title: "Коллекция 1",
    path: "collection1",
    text: "Приталенное платье мини мятного цвета в полу-спортивном стиле. Выполнено из джерси, рукава из мерцающего желтого крепа. На юбке вставки из гофре плиссе разных цветов. Мятный и розовый лампасы придают платью спортивное направление. По спинке длинная леопардовая молния.",
  },
  {
    id: "204",
    src: collectionFoto,
    title: "Коллекция 2",
    path: "collection2",
    text: "Приталенное платье мини мятного цвета в полу-спортивном стиле. Выполнено из джерси, рукава из мерцающего желтого крепа. На юбке вставки из гофре плиссе разных цветов. Мятный и розовый лампасы придают платью спортивное направление. По спинке длинная леопардовая молния.",
  },
];

export { productsBD, categoryBD, collectionBD };
