import {
  product1,
  product2,
  product3,
  product4,
  dress1,
  dress2,
  dress3,
  dress4,
  dress5,
  dress6,
  dress7,
  categorySaleFoto,
  categoryFoto1,
  categoryFoto2,
  categoryFoto3,
  categoryFoto4,
  categoryFoto5,
  categoryFoto6,
  categoryFoto7,
  categoryFoto8,
  collectionFoto,
} from "./constants";

const productsBD = [
  {
    img: categorySaleFoto,
    title: "Распродажа",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "12",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "sale",
    collection: "cruise",
  },
  {
    img: product1,
    title: "Коралловое платье с плиссированными вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: 15500,
    price: 8000,
    id: "1",
    isInBasket: true,
    isInFavorite: true,
    isInOrder: false,
    category: "dress",
    collection: "urban",
  },
  {
    img: product2,
    title: "Брюки с эффектом джинсовой ткани",
    article: "PP29",
    size: "S",
    height: 160,
    quantity: 1,
    discount: "",
    price: 20000,
    id: "2",
    isInBasket: true,
    isInFavorite: true,
    isInOrder: true,
    category: "pant",
    collection: "punk",
  },
  {
    img: product3,
    title: "Коралловое платье с плиссированными вставками",
    article: "PP13",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 18000,
    id: "3",
    isInBasket: true,
    isInFavorite: true,
    isInOrder: true,
    category: "dress",
    collection: "cruise",
  },
  {
    img: product4,
    title: "Бордовое платье [x1]",
    article: "PP13",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 9000,
    id: "4",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: true,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress1,
    title: "Синее плиссированное платье с вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "5",
    isInBasket: false,
    isInFavorite: true,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress2,
    title: "Розовое плиссированное платье с вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "6",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress3,
    title: "Темно-синее платье с воланами",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "7",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress4,
    title: "Песочное платье с плиссированными вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "8",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress5,
    title: "Розовое плиссированное платье с вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "9",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress6,
    title: "Бордовое платье",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "10",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: dress7,
    title: "Коралловое платье с плиссированными вставками",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "11",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "dress",
    collection: "cruise",
  },
  {
    img: categoryFoto1,
    title: "Жакеты",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "13",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "jackets",
    collection: "cruise",
  },
  {
    img: categoryFoto2,
    title: "Юбки",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "14",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "skirts",
    collection: "urban",
  },
  {
    img: categoryFoto3,
    title: "Свадебные платья",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "15",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "wedding",
    collection: "urban",
  },
  {
    img: categoryFoto4,
    title: "Блузки",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "16",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "blouses",
    collection: "punk",
  },
  {
    img: categoryFoto5,
    title: "Костюмы",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "17",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "costumes",
    collection: "cruise",
  },
  {
    img: categoryFoto6,
    title: "Свитеры",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "18",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "sweaters",
    collection: "cruise",
  },
  {
    img: categoryFoto7,
    title: "Верхняя одежда",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "19",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "outerwear",
    collection: "cruise",
  },
  {
    img: categoryFoto8,
    title: "Футболки",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "20",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "tshirt",
    collection: "punk",
  },
  {
    img: collectionFoto,
    title: "Олимпийки",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "21",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "olympians",
    collection: "punk",
  },
  {
    img: collectionFoto,
    title: "Худи и свитшоты",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "23",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "hoodies",
    collection: "punk",
  },
  {
    img: collectionFoto,
    title: "Водолазки",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "24",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "turtlenecks",
    collection: "punk",
  },
  {
    img: collectionFoto,
    title: "Аксессуары",
    article: "А0118",
    size: "L",
    height: 160,
    quantity: 1,
    discount: "",
    price: 35000,
    id: "25",
    isInBasket: false,
    isInFavorite: false,
    isInOrder: false,
    category: "accessories",
    collection: "urban",
  },
];

export default productsBD;
